/**
 * Fractional-index order key helpers.
 *
 * ## Alphabet
 * 62 characters in ASCII lexicographic order:
 * `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`
 * i.e. digits < uppercase < lowercase.
 *
 * `compareOrderKeys` is a pure lexicographic comparator on these strings.
 * This coincides with native JS string comparison for strings composed
 * entirely of the alphabet characters.
 *
 * ## Invariant
 * No key generated by `keyBetween` ends with `CHARS[0]` (`'0'`).  This
 * guarantees that for any two distinct valid keys `lo < hi` there is
 * always room to insert without renumbering existing keys.
 *
 * ## Choice rationale
 * Base-62 with the ASCII lexicographic ordering is a well-understood,
 * portable scheme: keys are short, human-readable, and survive round-trips
 * through YAML frontmatter without quoting.  The no-trailing-`0` invariant
 * is the minimal constraint that ensures infinite divisibility.
 */
const CHARS = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
const N = CHARS.length; // 62
const MID_IDX = Math.floor(N / 2); // 31 → 'P'

function ci(c: string): number {
  const i = CHARS.indexOf(c);
  if (i < 0) throw new Error(`Invalid order-key character: ${JSON.stringify(c)}`);
  return i;
}

function charAt(s: string, i: number): string {
  return s.charAt(i); // '' when out of range
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Lexicographic comparator for order keys.
 * Returns a negative number if `a < b`, positive if `a > b`, `0` if equal.
 * Consistent with the ordering produced by `keyBetween`.
 */
export function compareOrderKeys(a: string, b: string): number {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
}

/**
 * Generate a fractional-index order key strictly between `lo` and `hi`.
 *
 * - `keyBetween(undefined, undefined)` — returns a single mid-alphabet char.
 * - `keyBetween(lo, undefined)`        — returns a key greater than `lo`.
 * - `keyBetween(undefined, hi)`        — returns a key less than `hi`.
 * - `keyBetween(lo, hi)`               — returns a key strictly between them.
 *
 * Throws if `lo >= hi` (invalid range).
 * The result never ends in `'0'`; this invariant holds for all recursive
 * branches.
 */
export function keyBetween(lo?: string, hi?: string): string {
  if (lo !== undefined && hi !== undefined && lo >= hi) {
    throw new Error(
      `keyBetween: lo must be strictly less than hi (got ${JSON.stringify(lo)} >= ${JSON.stringify(hi)})`,
    );
  }
  return _between(lo ?? '', hi);
}

// ---------------------------------------------------------------------------
// Internal: recursive midpoint search
// ---------------------------------------------------------------------------

/**
 * Find a string strictly between `lo` (inclusive floor, '' = bottom) and
 * `hi` (exclusive ceiling, `undefined` = unbounded above).
 *
 * Result never ends in CHARS[0] ('0').
 */
function _between(lo: string, hi: string | undefined): string {
  // Unbounded above: append the mid character
  if (hi === undefined) {
    return lo + CHARS[MID_IDX]!;
  }

  // Find common prefix
  let i = 0;
  while (
    i < lo.length &&
    i < hi.length &&
    charAt(lo, i) === charAt(hi, i)
  ) {
    i++;
  }

  const prefix = lo.slice(0, i);
  const loTail = lo.slice(i);
  const hiTail = hi.slice(i);

  // hiTail must be non-empty: hi > lo (validated) and common prefix consumed,
  // so hi has at least one more character than the shared prefix.
  const hiFirst = hiTail.charAt(0);
  if (!hiFirst) {
    // Should never happen given lo < hi validation
    throw new Error('keyBetween: internal invariant violated (hiTail empty)');
  }
  const h0 = ci(hiFirst);

  if (loTail.length === 0) {
    // lo = prefix (lo is a proper prefix of hi)
    if (h0 > 1) {
      // Room between index 0 and h0: pick floor(h0/2) safely below hi
      return prefix + CHARS[Math.floor(h0 / 2)]!;
    }
    if (h0 === 1) {
      // hi = prefix + '1'…; insert prefix + '0' + MID_CHAR (avoids trailing '0')
      return prefix + CHARS[0]! + CHARS[MID_IDX]!;
    }
    // h0 === 0: hi = prefix + '0' + hiRest
    // By the no-trailing-0 invariant, hiRest is non-empty.
    const hiRest = hiTail.slice(1);
    return prefix + CHARS[0]! + _between('', hiRest.length > 0 ? hiRest : undefined);
  }

  // Both tails non-empty; loTail[0] !== hiTail[0] (common prefix exhausted)
  const loFirst = loTail.charAt(0);
  const l0 = ci(loFirst);

  if (h0 - l0 >= 2) {
    // Enough space between the two first characters
    return prefix + CHARS[Math.floor((l0 + h0) / 2)]!;
  }

  // h0 - l0 === 1: extend lo's subtree (unbounded upper)
  return prefix + CHARS[l0]! + _between(loTail.slice(1), undefined);
}
